language: ruby
rvm:
  - "2.2.1"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec